apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app-deployment
  labels:
    app: shopping-app
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
      - name: shopping-app
        image: grootkesare/shopping-app
        ports:
        - containerPort: 5173
