pipeline {
  agent any

  environment {
    DOCKER_REPO = "0x1luffy/3-tier-chat-app-kops"
    IMAGE_TAG = "${env.GIT_COMMIT.substring(0,7)}"
  }

  stages {

    stage('Clean Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('Checkout Code') {
      steps {
        git branch: 'master',
            url: 'https://github.com/0x1luffy/Kubernetes-Projects.git'
      }
    }

    stage('Build & Push Images') {
      steps {
        dir('Full-Stack-Chat-App') {
          sh """
          docker build -t ${DOCKER_REPO}:backend-${IMAGE_TAG} backend
          docker build -t ${DOCKER_REPO}:frontend-${IMAGE_TAG} frontend

          docker push ${DOCKER_REPO}:backend-${IMAGE_TAG}
          docker push ${DOCKER_REPO}:frontend-${IMAGE_TAG}
          """
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        dir('Full-Stack-Chat-App') {
          sh """
          sed -i 's|backend-__IMAGE_TAG__|backend-${IMAGE_TAG}|g' K8s/backend-deployment.yml
          sed -i 's|frontend-__IMAGE_TAG__|frontend-${IMAGE_TAG}|g' K8s/frontend-deployment.yml

          kubectl apply -f K8s/
          kubectl rollout status deployment/backend -n chat-app
          kubectl rollout status deployment/frontend -n chat-app
          """
        }
      }
    }
  }
}
