apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatapp-ingress
  namespace: chat-app
spec:
  rules:
  - host: chetancodes.dpdns.org
    http:
      paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5001

      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
